### ISSUE TITLE
Installation failed since app's minSdkVersion is newer than device's API level (API 23)

### ISSUE THREAD

**Issue by pokmis** [GitGarage/BLEMingleDroid#1]
I'm attempting to install BLEMingleDroid on an Android 6 (API level 23) device but I'm running into a "Installation failed since app's minSdkVersion is newer than device's API level (API 23)" error.

Can this code work with API Level 23 devices or is API Level 24 a hard requirement?

I'm not able to upgrade the OS on the device - Are there any tricks/patches I can make to the code to make it work?

**Comment by gitgarage** [comment]
Originally it was for 23, try the original commit:

https://github.com/GitGarage/BLEMingleDroid/tree/fc132003d03145c344ad21e6e967e82691679f23
